# CS 316 : Introduction to Deep Learning
## Lab 01 : Numpy Basics
### Dr. Abdul Samad

# Overview
Hello, students. In this lab, we will go over the fundamentals of Numpy. We'll start with data manipulation and then move on to numpy methods and operators.

Objectives:
1) Understanding the Basic of numpy Library for Deep Learning 
2) Applying numpy operations on different tensors

# Setup

In [2]:
# Import numpy using the alias np
import numpy as np
from PIL import Image
np.__version__

'1.23.5'

# 1 - Data Manipulation

A tensor represents a (possibly multi-dimensional) array of numerical values. With one axis, a tensor corresponds (in math) to a vector. With two axes, a tensor corresponds to a matrix. Tensors with more than two axes do not have special mathematical names.


## Creating Numpy Arrays-Matrices-Tensors

We can use arange to create a row vector x containing the first 12 integers starting with 0, though they are created as floats by default. Each of the values in a tensor is called an element of the tensor. For instance, there are 12 elements in the tensor x. Unless otherwise specified, a new tensor will be stored in main memory and designated for CPU-based computation.
<h3><center>Representation of Creating Vectors</center></h3>

<div>
<center>
<img src="arrange.png" width="840" />
</center>
</div>

In [3]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

We can access a tensor’s shape (the length along each axis) by inspecting its shape property.

In [4]:
x.shape

(12,)

If we just want to know the total number of elements in a tensor, i.e., the product of all of the shape elements, we can inspect its size. Because we are dealing with a vector here, the single element of its shape is identical to its size.

In [5]:
x.size

12

To change the shape of a tensor without altering either the number of elements or their values, we can invoke the reshape function. For example, we can transform our tensor, x, from a row vector with shape (12,) to a matrix with shape (3, 4). This new tensor contains the exact same values, but views them as a matrix organized as 3 rows and 4 columns. To reiterate, although the shape has changed, the elements have not. Note that the size is unaltered by reshaping. Notice that when we use matrices we also use capital letters.

<h3><center>Reshaping Representation</center></h3>

<div>
<center>
<img src="reshape.png" width="840" />
</center>
</div>


In [6]:
X = x.reshape(3, 4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Furthemore, Numpy also provides the option of transposing a array-matrix-tensor.

<h3><center>Transpose Representation</center></h3>

<div>
<center>
<img src="transpose.png" width="840" />
</center>
</div>



In [7]:
np.arange(0,10).reshape((2,5)).T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In some scenarios we may require a array-matrix-tensor of all ones or zero. We can easily create them use the "ones" and "zeros" method.

<h3><center>Creating vectors with 0s or 1s or random values</center></h3>

<div>
<center>
<img src="zeros.png" width="840" />
</center>
</div>


In [8]:
X = np.zeros((2, 7))
X

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [9]:
X = np.ones((4, 7))
X

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

We can also construct special matrices such as the Diagonal and Identity Matrx.

In [10]:
D = np.diag([2,3,4])
D

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [11]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

To create tensor we just add an extra dimension to the shape of numpy object. Lets make a 3x3x3 tensor of all ones.

We can also a new axis to an existing array , matrix or tensor. using `np.newaxis`.

In [12]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Often, we want to randomly sample the values for each element in a tensor from some probability distribution. For example, when we construct arrays to serve as parameters in a neural network, we will typically initialize their values randomly. The following snippet creates a tensor with shape (3, 4). Each of its elements is randomly sampled from a standard Gaussian (normal) distribution with a mean of 0 and a standard deviation of 1. We can see that every time we run this cell it creates new random numbers.

In [13]:
np.random.normal(0, 1, size=(3, 4))

array([[-0.95346618,  1.84632811, -0.37899275,  0.33644032],
       [ 2.38322021, -0.35847745, -1.09167934,  0.47007069],
       [-0.09855309,  1.65132216,  0.73439974, -0.27294368]])

Numpy also provides options to sample from other distributions such as the uniform distribution.

In [14]:
np.random.rand(5,5)

array([[0.06383495, 0.01394653, 0.27321092, 0.0979192 , 0.61454952],
       [0.64207737, 0.01447337, 0.84093242, 0.47388159, 0.10409953],
       [0.77283729, 0.69896313, 0.69676989, 0.08339845, 0.91308974],
       [0.58360497, 0.25397598, 0.30464496, 0.50791404, 0.6157033 ],
       [0.37086029, 0.18692514, 0.70711155, 0.63287826, 0.7859386 ]])

In [15]:
np.random.uniform(size=(5,5))

array([[0.82821957, 0.45146059, 0.28743489, 0.01853985, 0.29944517],
       [0.55612686, 0.73147138, 0.01752668, 0.28061265, 0.39799121],
       [0.31736832, 0.7886995 , 0.02939367, 0.7487525 , 0.53074716],
       [0.48111726, 0.16829212, 0.46813275, 0.53717377, 0.20863296],
       [0.72469885, 0.48720854, 0.7946234 , 0.36352654, 0.91541278]])

In [16]:
np.random.randint(0,100,(5,5))

array([[49, 66, 15, 46, 70],
       [46, 95, 36, 54, 26],
       [28, 16, 34, 87, 89],
       [ 0, 50,  9, 13, 28],
       [ 8, 74, 82, 82, 34]])

## Indexing and Slicing

Just as in any other Python array, elements in a tensor can be accessed by index. As in any Python array, the first element has index 0 and ranges are specified to include the first but before the last element. As in standard Python lists, we can access elements according to their relative position to the end of the list by using negative indices.

Thus, [-1] selects the last element and [1:3] selects the second and the third elements as follows:

<h3><center>Indexing</center></h3>

<div>
<center>
<img src="indexing.png" width="840" />
</center>
</div>


In [17]:
X = np.arange(1,7).reshape(3, 2)
X[-1], X[0,1],X[1:3],X[0:2,0]

(array([5, 6]),
 2,
 array([[3, 4],
        [5, 6]]),
 array([1, 3]))

If we want to assign multiple elements the same value, we simply index all of them and then assign them the value. For instance, [0:2, :] accesses the first and second rows, where : takes all the elements along axis 1 (column). While we discussed indexing for matrices, this obviously also works for vectors and for tensors of more than 2 dimensions.

In [18]:
X[0:2, :] = 12
X

array([[12, 12],
       [12, 12],
       [ 5,  6]])

In addition to specifying the bounds for accessing the array, we can also specify the stepsize.

In [19]:
r = np.random.rand(5,5)
print(r)


[[0.36256233 0.37662779 0.09127963 0.49486547 0.26218825]
 [0.32837855 0.3424456  0.46954207 0.64801761 0.17637421]
 [0.76181134 0.68076981 0.49621911 0.54007164 0.22167498]
 [0.92910466 0.76095714 0.0190784  0.61162068 0.60639252]
 [0.41253329 0.64273025 0.03526159 0.86815491 0.95930669]]


Here we are accessing all the rows, but only columns 0,2 and because 4 is the maximum bound and 2 is step size.

In [20]:
r[:,0:4:2]

array([[0.36256233, 0.09127963],
       [0.32837855, 0.46954207],
       [0.76181134, 0.49621911],
       [0.92910466, 0.0190784 ],
       [0.41253329, 0.03526159]])

We can also perform the above operation by using `np.arange` instead of providing the indices.

In [21]:
r[:,np.arange(0,4,2)]

array([[0.36256233, 0.09127963],
       [0.32837855, 0.46954207],
       [0.76181134, 0.49621911],
       [0.92910466, 0.0190784 ],
       [0.41253329, 0.03526159]])

## Utilizing what we Learned uptil now

We can use the skills that we have learned up until now to create a checkerboard.

In [22]:
# Create a checkerboard
z = np.zeros((8,8))
# Start from the second row, and skip every alternate row.
# Start from the first column, and skip every alternate column.
z[1::2,::2]=1
print(z)

# Start from the first row, and skip every alternate row.
# Start from the second column, and skip every alternate column.
z[::2,1::2]=1
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


We can also add a border of zeros to a matrix of ones.

In [23]:
# Working with borders and adding padding
image = np.ones((10,10))
# For all rows, assign first and last column zero.
image[:,[0,-1]]=0
print(image)
# For the first and last rows,assign all columns zero.
image[[0,-1],:]=0
print(image)

[[0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 2 - Numpy Operators



In this portion of the lab, we will see at some of the numpy operators. Understanding these will allow you to make your own neural network.

## Vectorized Operations



You may have noticed that numpy arrays have the restriction of just one data type. This homogeneity allows us to apply mathematical operations on each of the element in a numpy array at the same time. Suppose I want to add 2 matrices $A,B$ together, I can either iterate 1 by 1 and compute the result for each value or use numpy and do it together. I can do this operation using `np.add(A,B)` or more succinctly `A+B`. They both generate the same result.

<h3><center>Addition Representation</center></h3>

<div>
<center>
<img src="addition.png" width="840" />
</center>
</div>

<h3><center>Scalar multiplication Representation</center></h3>

<div>
<center>
<img src="scalarmultiplication.png" width="840" />
</center>
</div>

In [24]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,1],[1,1]])
print(np.add(A,B))
#it's better to only use the numpy library
print(A+B)

[[2 3]
 [4 5]]
[[2 3]
 [4 5]]


We can use other operators as well like
1. Subtraction : `np.subtract(A,B)` or `A-B`
2. Multiplication : `np.multiply(A,B)` or `A * B`. **Note that this is element-wise multiplication (Hamdard Product). This is not the same as Matrix Multiplication.**
3. Division: `np.divide(A,B)` or `A/B`.

## Element-Wise Operators
Similarly, we also have element-wise operations

1. Square: `np.square(A)`
2. Square Root: `np.sqrt(A)`. 
3. Floor: `np.floor(A)`
4. Ceil `np.ceil(A)`
5. Absolute Value: `np.abs(A)`
6. Exponential: `np.exp(A)`

## Examples of Operations

In [25]:
# Subtraction

Revenue = np.array([1200,2400,3000,4000,5000,5500])
Cost= np.array([1000,2000,2400,3450,4500,4600])

Profit = np.subtract(Revenue,Cost)
print("Subtracting revenue and profit:", Profit)

# Multiplication

Units_Sold = np.array([100,50,300,40,50,550])
Price = np.array([12,48,10,100,100,10])
Rev = np.multiply(Units_Sold,Price)
print("Multiplying the units sold with price:",Rev)


# Division

Prices = np.divide(Rev,Units_Sold)
print("Dividing revenue by units sold to get the price: ",Prices)

# Square

A = np.arange(-3,4)
print("A:",A)
squaredA = np.square(A)
print("A.^2:",squaredA)


# Square root

sqrt_squaredA = np.sqrt(squaredA)
print("Sqrt(A.^2):",sqrt_squaredA)

# Floor A
A = np.random.uniform(0,100,5)
print("A:",A)
floor_A = np.floor(A)
print("Floor A",floor_A)


ceil_A = np.ceil(A)
print("Floor A",ceil_A)

Subtracting revenue and profit: [200 400 600 550 500 900]
Multiplying the units sold with price: [1200 2400 3000 4000 5000 5500]
Dividing revenue by units sold to get the price:  [ 12.  48.  10. 100. 100.  10.]
A: [-3 -2 -1  0  1  2  3]
A.^2: [9 4 1 0 1 4 9]
Sqrt(A.^2): [3. 2. 1. 0. 1. 2. 3.]
A: [31.37888422 31.03854821 53.62061271 87.74991194 78.80251093]
Floor A [31. 31. 53. 87. 78.]
Floor A [32. 32. 54. 88. 79.]


Element wise exponentiation of an array with Numpy. Applying $e^a$ for every element $a$ in $A$

In [26]:
x = np.array([0,1,2,3,4,5,6,7])
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

## Combining Numpy Operators




Exponentiation is a useful operation which is used in the sigmoid activation function. Sigmoid function is defined as follows:
$$\frac{1}{1+e^{-x}}$$
We can use `np.exp(A)` to take $e^x$ on every element $x$. 
The below example implements this Sigmoid function using exponentiation.
<br>


In [27]:
def sigmoid(x):
	a = np.exp(-x)
	b = np.add(1,a)
	d = np.divide(1,b)
	return d

output_from_layer = np.array([-2,-1,0,1,2])
output_after_sigmoid = sigmoid(output_from_layer)

print(output_after_sigmoid)

[0.11920292 0.26894142 0.5        0.73105858 0.88079708]


Batch Normalization is a regularization technique that allows a neural network to learn a more generalised model. In Batch Normalization, you subtract the mean and divide by the standard deviation.

In [28]:
r = np.random.random((5,5))
print(r)
def z_score(mat):
    print(f"Mean : {np.mean(mat)} ; Std : {np.std(mat)}")
    return (mat - np.mean(mat))/np.std(mat)
print(z_score(r))

[[0.41476232 0.53104724 0.69764049 0.1052731  0.62911603]
 [0.30261138 0.3694026  0.98557175 0.06843421 0.49047204]
 [0.03862738 0.94934956 0.69076689 0.30047192 0.31828104]
 [0.23433397 0.81878014 0.34836753 0.14155445 0.80445759]
 [0.08273717 0.04348872 0.65536394 0.18307665 0.79131441]]
Mean : 0.43981210143302435 ; Std : 0.2925523553071129
[[-0.08562497  0.31185918  0.88130682 -1.1435184   0.64707708]
 [-0.46897835 -0.24067317  1.86551103 -1.26944079  0.17316537]
 [-1.37132625  1.74169665  0.85781156 -0.47629142 -0.41541644]
 [-0.70236361  1.29538537 -0.31257505 -1.01950178  1.24642814]
 [-1.22055051 -1.35470924  0.73679749 -0.87757095  1.20150224]]


## np.nan vs np.inf

One thing that should be noted is that `np.nan` is different from `np.inf`. `np.inf` represents positive infinity whereas `np.nan` represents an invalid value. Furthemore, you cannot perform any operations with `np.nan` values. 

We can see that when `np.inf` is compared with 0, the answer is True. However, when `np.nan` is compared with `np.inf`, the answer is False.

In [29]:
# Working with np.nan and np.Inf
print(0*np.inf)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan > np.inf)
print(np.nan < np.nan)
print(np.nan - np.nan)
print(np.inf > 0)

nan
False
False
False
False
nan
True


## Reduction



Sometimes we want to simplify our data. We might be dealing with images and want to convert it into grayscale hence we would need to take the average of the RGB channels. This simplification of data is known as _reduction_. We can perform it on multiple axis, and have functions like sum, average and median. We will motivate this understanding of how we can use axis using an example of pixels. The screen that you have has a width and height. And each pixel has an RGB value.

<h3><center>Reduction Representation</center></h3>

<div>
<center>
<img src="reduction.png" width="840" />
</center>
</div>

In [30]:
pixels = np.array([
        [[100,200,220],[110,110,110],[120,100,80]]
         ,[[0,0,0],[255,250,250],[30,50,70]]])
# We have 2 rows, with 3 columns, and each (row,column) pair has 3 values. RGB. The pixel has width 3, and height 2
pixels.shape

(2, 3, 3)

Suppose we want to take the sum of each row, then our axis would be 0 (Row axis)

In [31]:
np.sum(pixels,axis=0)

array([[100, 200, 220],
       [365, 360, 360],
       [150, 150, 150]])

If we want to take median of each column, we can take it on axis 1. (Column axis)

In [32]:
np.median(pixels,axis=1)

array([[110., 110., 110.],
       [ 30.,  50.,  70.]])

Suppose we want to convert the image into grayscale. Then we will take the average of the R,G,B pixels. Hence our axis will be 2.

In [33]:
np.average(pixels,axis=2)

array([[173.33333333, 110.        , 100.        ],
       [  0.        , 251.66666667,  50.        ]])

In [34]:
A=np.arange(10).reshape(2,5)
print(A)
print("Shape of A = ",A.shape)
print(np.max(A,axis=1))

[[0 1 2 3 4]
 [5 6 7 8 9]]
Shape of A =  (2, 5)
[4 9]


There exists other functions as well. Like max. You can also apply without specifying the axis. In that case, it will be applied to each element in the matrix.

In [35]:
np.max(pixels)

255

Numpy also provides functions which ignore Nan values when performing operations such as computing the mean or median.

In [36]:
A = np.asarray([0,np.nan,1])
print(np.nanmean(A))
print(np.nanmedian(A))
print(np.nansum(A))

0.5
0.5
1.0


## Non reduction




We can sometimes find it can be useful to keep the number of axes unchanged when invoking the function for calculating the sum or mean. In that case, we can set `keepdims = True` and this will preserve our dimensions.

In [37]:
A = np.arange(20).reshape(5, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [38]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

array([[ 6],
       [22],
       [38],
       [54],
       [70]])

For instance, since sum_A still keeps its two axes after summing each row, we can divide `A` by `sum_A` with broadcasting.

In [39]:
A / sum_A

array([[0.        , 0.16666667, 0.33333333, 0.5       ],
       [0.18181818, 0.22727273, 0.27272727, 0.31818182],
       [0.21052632, 0.23684211, 0.26315789, 0.28947368],
       [0.22222222, 0.24074074, 0.25925926, 0.27777778],
       [0.22857143, 0.24285714, 0.25714286, 0.27142857]])

If we want to calculate the cumulative sum of elements of A along some axis, say axis=0 (row by row), we can call the `cumsum` function. This function will not reduce the input tensor along any
axis.

In [40]:
A.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36],
       [40, 45, 50, 55]])

## Dot Product



So far, we have only performed elementwise operations, sums, and averages. We can now move on to the domain of Linear Algebra. One of the most fundamental operations is the dot product. Given two vectors $x, y \in  \mathbb{R}^d$, their _dot product_ $\mathbf{x}^⊤\mathbf{y}$ (or $\langle x, y\rangle$) is a sum over the products of the elements at the same position
$$\mathbf{x}^⊤\mathbf{y} = \sum_{i=1}^{d} x_i y_i$$

<h3><center>Dot Product Representation</center></h3>

<div>
<center>
<img src="dot1.png" width="840" />
</center>
</div>

<h3></h3>

<div>
<center>
<img src="dot2.png" width="840" />
</center>
</div>

In [41]:
x = np.arange(4)
y = np.ones(4)
# We use the np.dot function for dot products
x,y, np.dot(x,y)

(array([0, 1, 2, 3]), array([1., 1., 1., 1.]), 6.0)

Dot products are useful in a wide range ofcontexts. For example, given some set of values, denoted by a vector $x \in \mathbb{R}^d$ and a set of weights denoted by $w \in \mathbb{R}^d$, the weighted sum of the values in $x$ according to the weights $w$ could be expressed as the dot product $\mathbf{x}^⊤\mathbf{w}$. When the weights are
non-negative and sum to one (i.e., ($\sum_{i=1}^{d} w_i = 1$), the dot product expresses a _weighted average._
)

## Broadcasting

Arrays with different sizes cannot be added, subtracted, or generally be used in arithmetic. A way to overcome this is to duplicate the smaller array so that it is the dimensionality and size as the larger array. This is called array broadcasting and is available in NumPy when performing array arithmetic, which can greatly reduce and simplify your code.

<h3><center>Broadcasting Representation</center></h3>

<div>
<center>
<img src="broadcasting.png" width="840" />
</center>
</div>


In [42]:
# adding a sclar to array  
A = np.array([1,2,3])
b= 3.0
print(A+b)

[4. 5. 6.]


In [43]:
# adding a sclar to matrix
A = np.array([[1,2,3],[1,2,3]])
print(A)
b= 3.0
print(A+b)

[[1 2 3]
 [1 2 3]]
[[4. 5. 6.]
 [4. 5. 6.]]


In [44]:
A = np.array([[1,2,3],[1,2,3]])
print(A)
B=np.array([1,1,3]).reshape(1,3)
print(A+B)


[[1 2 3]
 [1 2 3]]
[[2 3 6]
 [2 3 6]]


## Aggregation

Additional benefits NumPy gives us are aggregation functions:

<h3><center>Aggregation Representation in Vectors</center></h3>

<div>
<center>
<img src="aggregationvectors.png" width="840" />
</center>
</div>


In addition to min, max, and sum, you get all the greats like mean to get the average, prod to get the result of multiplying all the elements together, std to get standard deviation, and plenty of others.

We can aggregate matrices the same way we aggregated vectors:

<h3><center>Aggregation Representation in Matrices</center></h3>

<div>
<center>
<img src="aggregation.png" width="840" />
</center>
</div>


In [45]:
# In Vector
a = np.arange(1,4)
a.min(),a.max(),a.sum()

(1, 3, 6)

In [46]:
# In Matrices
a = np.arange(1,7).reshape(3,2)
a.min(),a.max(),a.sum()

(1, 6, 21)

However, things get a little tricky when axis is involved.
<h3><center>Aggregation Representation in Matrices</center></h3>

<div>
<center>
<img src="aggregationaxis.png" width="840" />
</center>
</div>

In [47]:
# In Matrices
a = np.arange(1,7).reshape(3,2)
a.min(axis=0),a.max(axis=0),a.sum(axis=0),a.min(axis=1),a.max(axis=1),a.sum(axis=1)

(array([1, 2]),
 array([5, 6]),
 array([ 9, 12]),
 array([1, 3, 5]),
 array([2, 4, 6]),
 array([ 3,  7, 11]))

## argmax vs max and argmin vs min
argmax returns the index of maximum value and max returns the value. Similarly, argmin return the index of minimum value and min returns the value.

In [48]:
# Argmin and Argmax
z = np.random.uniform(0,10,10)
z[np.argmin(z)]=100
print(z)

[  3.79318366   1.45348853   6.00230324   7.71141536   1.01444892
   7.34869033 100.           1.7125098    4.06125921   9.80584156]


Let's say we want to find the closet value in the array A to the randomnly generated value. We can use the `np.argmin` for this purpose.

In [49]:
z = np.arange(100)
point = np.random.uniform(0,100)
index = np.argmin(np.abs(z-point))
print(f'Point is {point} is close to {z[index]}')

Point is 26.84095671815455 is close to 27


## 3-Dimensional Tensors
When you printing a 3-dimensional NumPy array, the text output visualizes the array differently than stored in memory. here is how it will be stored in Memory.

<div>
<center>
<img src="moredimensions.png" width="840" />
</center>
</div>

NumPy’s order for printing n-dimensional arrays is that the last axis is looped over the fastest, while the first is the slowest. Which means that np.ones((4,3,2)) would be printed as:

In [50]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [51]:
np.random.random((4,3,2))

array([[[0.71742048, 0.22066025],
        [0.3544689 , 0.39306487],
        [0.01173639, 0.03763743]],

       [[0.41210745, 0.56063978],
        [0.84622183, 0.97798881],
        [0.51291966, 0.54821589]],

       [[0.2748304 , 0.69281295],
        [0.04801771, 0.38116412],
        [0.46495034, 0.90866394]],

       [[0.65876798, 0.80593594],
        [0.01168808, 0.89222466],
        [0.90546341, 0.62386472]]])